# Instalando os pacotes
```{r}
# install.packages("rpart")
library(rpart)
# install.packages("rpart.plot")
library(rpart.plot)
# install.packages("dplyr")
library(dplyr)
# install.packages("outliers")
library(outliers)
# install.packages("base")
library(base)
# install.packages("base")
library(ggplot2)
# install.packages("santoku")
library(santoku)
```

# Copiar dataset limpo
# Executar o arquivo LimparDados.rmd, ele cria o df_limpo
```{r}
dataset_comp_range <- df_limpo
```


# Transformando os dados em ranges
```{r}
dataset_comp_range$ConvertedCompYearly <- chop_equally(dataset_comp_range$ConvertedCompYearly, 10, raw = FALSE)
dataset_comp_range$YearsCodePro <- as.numeric(dataset_comp_range$YearsCodePro)
dataset_comp_range$YearsCodePro <- chop_equally(dataset_comp_range$YearsCodePro, 10, raw = TRUE)

```


# Transformando os dados em categorias
```{r}
dataset_comp_range$ConvertedCompYearly <- as.factor(dataset_comp_range$ConvertedCompYearly)
dataset_comp_range$OrgSize <- as.factor(dataset_comp_range$OrgSize)
dataset_comp_range$YearsCodePro <- as.factor(dataset_comp_range$YearsCodePro)
dataset_comp_range$YearsCode <- as.factor(dataset_comp_range$YearsCode)
dataset_comp_range$Country <- as.factor(dataset_comp_range$Country)
dataset_comp_range$RemoteWork <- as.factor(dataset_comp_range$RemoteWork)
```

# Criando a Arvore de decisao
```{r}
datasetTree <- head(dataset_comp_range, nrow(dataset_comp_range))
modelo_salario <- rpart(ConvertedCompYearly~YearsCodePro+OrgSize+Country+Age+RemoteWork,
                                  data=datasetTree,
                                  method="class",
                                  control=rpart.control(minsplit = 1,
                                                        xval = 9),
                                  parms=list(split="Information"))
modelo_salario
```


# Plot da Árvore
```{r}
arvore_decisao <- rpart.plot(modelo_salario, type = 2)
```


# Criando a Arvore de decisao
#
```{r}
modelo_salario_idade <- rpart(ConvertedCompYearly~YearsCodePro+OrgSize+Age+RemoteWork,
                                  data=datasetTree,
                                  method="class",
                                  control=rpart.control(minsplit = 1,
                                                        xval = 9),
                                  parms=list(split="Information"))
modelo_salario_idade
```


# Plot da Árvore
```{r}
arvore_decisao_idade <- rpart.plot(modelo_salario_idade, type = 2)
```
